version: '2'
networks:
  weberhome_lan:
    external: true
services:
  smarthome:
    image: neonox31/node-red-smarthome:latest
    privileged: true
    restart: always
    ports:
      - "1880:1880"
    networks:
      - weberhome_lan
    environment:
      - NODE_OPTIONS=--max_old_space_size=1024
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/node-red-smarthome:/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rvm
    labels:
      - "traefik.enable=true"
      - "traefik.backend=smarthome"
      - "traefik.port=1880"
      - "traefik.frontend.rule=Host:node-red.weberhome.lan, node-red"
